"""Central configuration for the AI Database.

Everything tunable lives here so the rest of the code stays boring.
"""

# --- Timezones -------------------------------------------------------------
DISPLAY_TZ = "Europe/London"      # times shown in reports
MARKET_TZ = "America/New_York"    # US data release timezone

# --- Data sources ----------------------------------------------------------
# Official ForexFactory calendar feed (published by FairEconomy, free, no key).
CALENDAR_URLS = [
    "https://nfs.faireconomy.media/ff_calendar_thisweek.json",
    "https://cdn-nfs.faireconomy.media/ff_calendar_thisweek.json",
]

# Gold. GC=F is COMEX gold futures; XAUUSD=X is the FX spot cross.
GOLD_SYMBOLS = ["GC=F", "XAUUSD=X"]
DXY_SYMBOLS = ["DX-Y.NYB"]          # dollar index, for context
YIELD_SYMBOLS = ["^TNX"]            # US 10y yield, gold's main driver

YAHOO_CHART = "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}"
STOOQ_CSV = "https://stooq.com/q/d/l/?s={symbol}&i=d"   # fallback, daily only

# Free RSS feeds. No API keys. Failures are tolerated individually.
NEWS_FEEDS = [
    ("Federal Reserve", "https://www.federalreserve.gov/feeds/press_all.xml"),
    ("Fed Speeches", "https://www.federalreserve.gov/feeds/speeches.xml"),
    ("US Treasury", "https://home.treasury.gov/rss/press.xml"),
    ("BLS", "https://www.bls.gov/feed/bls_latest.rss"),
    ("CNBC Economy", "https://www.cnbc.com/id/20910258/device/rss/rss.html"),
    ("CNBC Top News", "https://www.cnbc.com/id/100003114/device/rss/rss.html"),
    ("MarketWatch", "https://feeds.content.dowjones.io/public/rss/mw_topstories"),
    ("Yahoo Gold", "https://feeds.finance.yahoo.com/rss/2.0/headline?s=GC=F&region=US&lang=en-US"),
]

# --- Gold sensitivity weights ---------------------------------------------
# 0-10: how hard this release typically hits gold. Matched on the event title,
# longest key first, case-insensitive. Anything unmatched falls back to the
# calendar's own impact rating.
EVENT_WEIGHTS = {
    "federal funds rate": 10,
    "fomc statement": 10,
    "fomc press conference": 10,
    "fomc economic projections": 10,
    "cpi m/m": 10,
    "cpi y/y": 10,
    "core cpi m/m": 10,
    "non-farm employment change": 10,
    "core pce price index": 9,
    "pce price index": 8,
    "average hourly earnings": 8,
    "unemployment rate": 8,
    "fed chair": 8,
    "fed chairman": 8,
    "fomc meeting minutes": 7,
    "core ppi m/m": 6,
    "ppi m/m": 6,
    "core retail sales": 6,
    "retail sales m/m": 6,
    "ism manufacturing pmi": 6,
    "ism services pmi": 6,
    "benchmark payrolls revision": 6,
    "adp non-farm employment change": 6,
    "advance gdp q/q": 5,
    "prelim gdp q/q": 5,
    "final gdp q/q": 4,
    "treasury sec": 4,
    "jolts job openings": 4,
    "unemployment claims": 4,
    "flash manufacturing pmi": 4,
    "flash services pmi": 4,
    "consumer confidence": 3,
    "uom consumer sentiment": 3,
    "uom inflation expectations": 4,
    "fomc member": 3,
    "treasury currency report": 2,
    "10-y bond auction": 3,
    "30-y bond auction": 3,
}

IMPACT_FALLBACK = {"high": 6, "medium": 3, "low": 1, "holiday": 0}

# Weight at or above which an event is treated as market-moving for gold.
MATERIAL_WEIGHT = 4
# Weight at or above which we call it a "red folder" style headline risk.
MAJOR_WEIGHT = 8

# --- Risk bands ------------------------------------------------------------
RISK_BANDS = [
    (0, 25, "LOW", "Quiet tape. Normal conditions, no scheduled shock."),
    (25, 50, "MODERATE", "Some scheduled risk. Expect intraday noise around releases."),
    (50, 75, "HIGH", "Major scheduled event. Wide, fast moves and poor fills likely."),
    (75, 101, "EXTREME", "Top-tier event risk. Spreads widen, stops get run, direction is a coin flip on the print."),
]

# --- News relevance keywords ----------------------------------------------
NEWS_KEYWORDS = {
    "fed": 3, "fomc": 3, "powell": 3, "warsh": 3, "rate cut": 3, "rate hike": 3,
    "interest rate": 3, "monetary policy": 3, "inflation": 3, "cpi": 3,
    "pce": 3, "treasury yield": 3, "10-year": 2, "dollar": 3, "greenback": 2,
    "gold": 4, "bullion": 4, "safe haven": 3, "payrolls": 3, "jobs report": 3,
    "unemployment": 2, "tariff": 2, "recession": 2, "debt ceiling": 2,
    "geopolitic": 2, "war": 2, "sanction": 2, "central bank": 2, "yields": 2,
}

# --- Narrative -------------------------------------------------------------
# Optional. If GEMINI_API_KEY is set the write-up is generated by a model;
# otherwise a deterministic template is used. Everything else works either way.
GEMINI_MODEL = "gemini-2.5-flash"
GEMINI_URL = ("https://generativelanguage.googleapis.com/v1beta/models/"
              "{model}:generateContent")

SITE_TITLE = "Gold / USD Daily Risk Database"
